<?php

return [

    /*
    |--------------------------------------------------------------------------
    | eBay Developer Credentials
    |--------------------------------------------------------------------------
    |
    | Created at https://developer.ebay.com -> Your Account -> Application Keys.
    | Each environment (sandbox / production) has its own keyset and RuName.
    | The RuName ("Redirect URL name") is generated by eBay when you register
    | your accept/reject URLs under "User Tokens" -> "Add eBay Redirect URL".
    | Your accept URL must point to: {APP_URL}/ebay/callback
    |
    */

    'sandbox' => env('EBAY_SANDBOX', true),

    'client_id' => env('EBAY_CLIENT_ID'),        // App ID
    'client_secret' => env('EBAY_CLIENT_SECRET'), // Cert ID
    'dev_id' => env('EBAY_DEV_ID'),
    'ru_name' => env('EBAY_RU_NAME'),

    'default_marketplace' => env('EBAY_MARKETPLACE_ID', 'EBAY_US'),

    // Used when eBay cannot suggest a category from the product title.
    'fallback_category_id' => env('EBAY_FALLBACK_CATEGORY_ID'),

    // How many days back the order sync looks when importing eBay orders.
    'orders_lookback_days' => env('EBAY_ORDERS_LOOKBACK_DAYS', 30),

    // How many days back the return sync looks when importing eBay returns.
    'returns_lookback_days' => env('EBAY_RETURNS_LOOKBACK_DAYS', 30),

    // Ship-from address the "Create default policies" button uses when a store
    // has no inventory location yet. A US example is used by default — override
    // these in .env with your real warehouse address (city/postal must be valid
    // for the country, so non-US stores should set all five).
    'default_location' => [
        'name' => env('EBAY_LOCATION_NAME', 'Main Warehouse'),
        'address_line1' => env('EBAY_LOCATION_ADDRESS', '2025 Hamilton Ave'),
        'city' => env('EBAY_LOCATION_CITY', 'San Jose'),
        'state' => env('EBAY_LOCATION_STATE', 'CA'),
        'postal_code' => env('EBAY_LOCATION_POSTAL', '95125'),
        'country' => env('EBAY_LOCATION_COUNTRY', 'US'),
    ],

    /*
    |--------------------------------------------------------------------------
    | OAuth scopes requested when a user connects a store
    |--------------------------------------------------------------------------
    */

    'scopes' => [
        'https://api.ebay.com/oauth/api_scope/sell.inventory',
        'https://api.ebay.com/oauth/api_scope/sell.account',
        'https://api.ebay.com/oauth/api_scope/sell.fulfillment',
        'https://api.ebay.com/oauth/api_scope/commerce.identity.readonly',
    ],

    /*
    |--------------------------------------------------------------------------
    | Supported marketplaces
    |--------------------------------------------------------------------------
    */

    // "site" is the legacy numeric site ID, required by the Trading API that
    // the order sync falls back to (see EbayService::fetchLegacyOrders).
    'marketplaces' => [
        'EBAY_US' => ['label' => 'United States', 'currency' => 'USD', 'language' => 'en-US', 'site' => 0],
        'EBAY_GB' => ['label' => 'United Kingdom', 'currency' => 'GBP', 'language' => 'en-GB', 'site' => 3],
        'EBAY_CA' => ['label' => 'Canada', 'currency' => 'CAD', 'language' => 'en-CA', 'site' => 2],
        'EBAY_AU' => ['label' => 'Australia', 'currency' => 'AUD', 'language' => 'en-AU', 'site' => 15],
        'EBAY_DE' => ['label' => 'Germany', 'currency' => 'EUR', 'language' => 'de-DE', 'site' => 77],
        'EBAY_FR' => ['label' => 'France', 'currency' => 'EUR', 'language' => 'fr-FR', 'site' => 71],
        'EBAY_IT' => ['label' => 'Italy', 'currency' => 'EUR', 'language' => 'it-IT', 'site' => 101],
        'EBAY_ES' => ['label' => 'Spain', 'currency' => 'EUR', 'language' => 'es-ES', 'site' => 186],
    ],

    /*
    |--------------------------------------------------------------------------
    | Item conditions selectable when syncing a product
    |--------------------------------------------------------------------------
    */

    'conditions' => [
        'NEW' => 'New',
        'NEW_OTHER' => 'New (other)',
        'LIKE_NEW' => 'Like new',
        'USED_EXCELLENT' => 'Used - Excellent',
        'USED_VERY_GOOD' => 'Used - Very good',
        'USED_GOOD' => 'Used - Good',
        'USED_ACCEPTABLE' => 'Used - Acceptable',
        'FOR_PARTS_OR_NOT_WORKING' => 'For parts / not working',
    ],
];
