<?php

return [

    /*
    |--------------------------------------------------------------------------
    | eBay Developer Credentials
    |--------------------------------------------------------------------------
    |
    | Created at https://developer.ebay.com -> Your Account -> Application Keys.
    | Each environment (sandbox / production) has its own keyset and RuName.
    | The RuName ("Redirect URL name") is generated by eBay when you register
    | your accept/reject URLs under "User Tokens" -> "Add eBay Redirect URL".
    | Your accept URL must point to: {APP_URL}/ebay/callback
    |
    */

    'sandbox' => env('EBAY_SANDBOX', true),

    'client_id' => env('EBAY_CLIENT_ID'),        // App ID
    'client_secret' => env('EBAY_CLIENT_SECRET'), // Cert ID
    'dev_id' => env('EBAY_DEV_ID'),
    'ru_name' => env('EBAY_RU_NAME'),

    'default_marketplace' => env('EBAY_MARKETPLACE_ID', 'EBAY_US'),

    // Used when eBay cannot suggest a category from the product title.
    'fallback_category_id' => env('EBAY_FALLBACK_CATEGORY_ID'),

    /*
    |--------------------------------------------------------------------------
    | OAuth scopes requested when a user connects a store
    |--------------------------------------------------------------------------
    */

    'scopes' => [
        'https://api.ebay.com/oauth/api_scope/sell.inventory',
        'https://api.ebay.com/oauth/api_scope/sell.account',
        'https://api.ebay.com/oauth/api_scope/commerce.identity.readonly',
    ],

    /*
    |--------------------------------------------------------------------------
    | Supported marketplaces
    |--------------------------------------------------------------------------
    */

    'marketplaces' => [
        'EBAY_US' => ['label' => 'United States', 'currency' => 'USD', 'language' => 'en-US'],
        'EBAY_GB' => ['label' => 'United Kingdom', 'currency' => 'GBP', 'language' => 'en-GB'],
        'EBAY_CA' => ['label' => 'Canada', 'currency' => 'CAD', 'language' => 'en-CA'],
        'EBAY_AU' => ['label' => 'Australia', 'currency' => 'AUD', 'language' => 'en-AU'],
        'EBAY_DE' => ['label' => 'Germany', 'currency' => 'EUR', 'language' => 'de-DE'],
        'EBAY_FR' => ['label' => 'France', 'currency' => 'EUR', 'language' => 'fr-FR'],
        'EBAY_IT' => ['label' => 'Italy', 'currency' => 'EUR', 'language' => 'it-IT'],
        'EBAY_ES' => ['label' => 'Spain', 'currency' => 'EUR', 'language' => 'es-ES'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Item conditions selectable when syncing a product
    |--------------------------------------------------------------------------
    */

    'conditions' => [
        'NEW' => 'New',
        'NEW_OTHER' => 'New (other)',
        'LIKE_NEW' => 'Like new',
        'USED_EXCELLENT' => 'Used - Excellent',
        'USED_VERY_GOOD' => 'Used - Very good',
        'USED_GOOD' => 'Used - Good',
        'USED_ACCEPTABLE' => 'Used - Acceptable',
        'FOR_PARTS_OR_NOT_WORKING' => 'For parts / not working',
    ],
];
